[tool.ruff]
# https://docs.astral.sh/ruff/configuration/
target-version = "py38"
line-length = 79
extend-exclude = [
  "_template",
  "*_pb2*.py*",
]
output-format = "concise"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/linter/#rule-selection
# pylint: https://github.com/astral-sh/ruff/issues/970
select = [
  "I",   # https://docs.astral.sh/ruff/rules/#isort-i
  "F",   # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "E",   # https://docs.astral.sh/ruff/rules/#error-e
  "W",   # https://docs.astral.sh/ruff/rules/#warning-w
  "PLC", # https://docs.astral.sh/ruff/rules/#convention-c
  "PLE", # https://docs.astral.sh/ruff/rules/#error-e_1
  "Q",   # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
  "A",   # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
  "UP",  # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "FA"   # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
]
ignore = [
  "E501", # line-too-long
]

[tool.ruff.lint.per-file-ignores]
"docs/**/*.*" = ["A001"]

[tool.ruff.lint.isort]
detect-same-package = false # to not consider instrumentation packages as first-party
known-first-party = ["opentelemetry"]
known-third-party = [
  "psutil",
  "pytest",
  "redis",
  "redis_opentracing",
  "opencensus",
]

