name: Contrib Repo Tests

on:
  push:
    branches-ignore:
      - 'release/*'
  pull_request:

env:
  CORE_REPO_SHA: 141a6a2e473ef7f0ec4915dfb71e3c0fa595283e

jobs:

  generatematrixjob:
    runs-on: ubuntu-latest
    outputs:
      generatematrixoutput: ${{ steps.generatematrixstep.outputs.matrix }}
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate Matrix
        id: generatematrixstep
        run: |
          python .github/workflows/generate_matrix.py

      - name: echo stuff
        run: echo $GITHUB_OUTPUT

  use-matrix:
    needs: generatematrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.generatematrixjob.outputs.generatematrixoutput) }}
    # runs-on: ${{ matrix.value.os }}

    steps:
      - name: echo stuff
        run: echo "${{ matrix.value.os }}
