name: Tests

on:
  push:
    branches-ignore:
      - 'release/*'
  pull_request:

env:
  CORE_REPO_SHA: 141a6a2e473ef7f0ec4915dfb71e3c0fa595283e

jobs:

  get_tox_ini_directory_python_versions:
    name: Get Python versions for each tox_ini_directory
    runs-on: ubuntu-latest
    outputs:
      tox_ini_directory_python_versions: ${{ steps.run_get_tox_ini_directory_python_versions_py.outputs.tox_ini_directory_python_versions }}
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run get_tox_ini_directory_python_versions.py
        id: run_get_tox_ini_directory_python_versions_py
        run: |
          python .github/workflows/get_tox_ini_directory_python_versions.py >> $GITHUB_OUTPUT

  run_tests:
    name: ${{ matrix.tox_ini_directory_python_versions.tox_ini_directory }} ${{ matrix.tox_ini_directory_python_versions.python_version }} ${{ matrix.os }}
    needs: get_tox_ini_directory_python_versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        tox_ini_directory_python_versions: ${{ fromJson(needs.get_tox_ini_directory_python_versions.outputs.tox_ini_directory_python_versions) }}

    steps:
      - name: echo stuff
        run: echo "${{ matrix.os }} ${{ matrix.tox_ini_directory_python_versions.tox_ini_directory }} ${{ matrix.tox_ini_directory_python_versions.python_version }}"
