name: Contrib Repo Tests

on:
  push:
    branches-ignore:
      - 'release/*'
  pull_request:

env:
  CORE_REPO_SHA: 141a6a2e473ef7f0ec4915dfb71e3c0fa595283e

jobs:

  generatematrixjob:
    runs-on: ubuntu-latest
    outputs:
      generatematrixoutput: ${{ steps.generatematrixstep.outputs.package_python_versions }}
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate Matrix
        id: generatematrixstep
        run: |
          python .github/workflows/get_package_python_versions.py

      - name: echo stuff
        run: echo $GITHUB_OUTPUT

  usematrixjob:
    run-name: "sdfsdf ${{ matrix.os }}"
    needs: generatematrixjob
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        package-python-version: ${{ fromJson(needs.generatematrixjob.outputs.generatematrixoutput) }}
    # runs-on: ${{ matrix.value.os }}

    steps:
      - name: echo stuff
        run: echo "${{ matrix.os }} ${{ matrix.package-python-version.tox_ini_directory }} ${{ matrix.package-python-version.python_version }}"
