name: Contrib Repo Tests

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:
env:
  CORE_REPO_SHA: 8d436dac6e6ea4643b342be80a7b5d188623a5dc

jobs:
  build:
    env:
      # We use these variables to convert between tox and GHA version literals
      py36: 3.6
      py37: 3.7
      py38: 3.8
      py39: 3.9
      pypy3: pypy-3.7
      RUN_MATRIX_COMBINATION: ${{ matrix.python-version }}-${{ matrix.package }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        python-version: [ py36, py37, py38, py39, pypy3 ]
        package: ["instrumentation", "exporter", "sdkextension", "propagator"]
        os: [ ubuntu-20.04, windows-2019 ]
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Checkout Core Repo @ SHA - ${{ env.CORE_REPO_SHA }}
        uses: actions/checkout@v2
        with:
          repository: open-telemetry/opentelemetry-python
          ref: ${{ env.CORE_REPO_SHA }}
          path: opentelemetry-python-core
      - name: Set up Python ${{ env[matrix.python-version] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env[matrix.python-version] }}
          architecture: 'x64'  # some packages such as cryptography do not publish pre-built wheels for x86
      - name: Cache python/tox
        uses: actions/cache@v2
        with:
          path: |
            .tox
            ~/.cache/pip
            c:\users\runneradmin\appdata\local\pip\cache
          key: v7-build-tox-cache-${{ env.RUN_MATRIX_COMBINATION }}-${{ hashFiles('tox.ini', 'gen-requirements.txt', 'dev-requirements.txt') }}
      - name: Install tox and pip
        run: pip install -U tox-factor pip
      # tox fails on windows and Python3.6 when tox dir is reused between builds so we remove it
      #- name: fix for windows + py3.6
      #  if: ${{ matrix.os == 'windows-2019' && matrix.python-version == 'py36' }} 
      #  shell: pwsh
      #  run: Remove-Item .\.tox\ -Force -Recurse -ErrorAction Ignore
      - name: run tox
        run: tox -f ${{ matrix.python-version }}-${{ matrix.package }} -- --benchmark-json=${{ env.RUN_MATRIX_COMBINATION }}-benchmark.json
      - name: Find and merge benchmarks
        # TODO: fix and enable on windows
        # TODO: Add at least one benchmark to every package type to remove this (#249)
        if: ${{ matrix.package == 'sdkextension' && matrix.os != 'windows-2019' }}
        run: >-
          jq -s '.[0].benchmarks = ([.[].benchmarks] | add)
          | if .[0].benchmarks == null then null else .[0] end'
          **/**/tests/*${{ matrix.package }}*-benchmark.json > output.json
      - name: Report on benchmark results
        # TODO: fix and enable on windows
        # TODO: Add at least one benchmark to every package type to remove this (#249)
        if: ${{ matrix.package == 'sdkextension' && matrix.os != 'windows-2019' }}
        uses: rhysd/github-action-benchmark@v1
        with:
          name: OpenTelemetry Python Benchmarks - Python ${{ env[matrix.python-version ]}} - ${{ matrix.package }}
          tool: pytest
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-items-in-chart: 100
          # Alert with a commit comment on possible performance regression
          alert-threshold: 200%
          fail-on-alert: true
          # Make a commit on `gh-pages` with benchmarks from previous step
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
  misc:
    strategy:
      fail-fast: false
      matrix:
        tox-environment: [ "docker-tests", "lint", "docs", "generate" ]
    name: ${{ matrix.tox-environment }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Checkout Core Repo @ SHA ${{ env.CORE_REPO_SHA }}
        uses: actions/checkout@v2
        with:
          repository: open-telemetry/opentelemetry-python
          ref: ${{ env.CORE_REPO_SHA }}
          path: opentelemetry-python-core
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install tox
        run: pip install -U tox
      - name: Install libsnappy-dev
        if: ${{ matrix.tox-environment == 'lint' }}
        run: sudo apt-get install -y libsnappy-dev
      - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
        uses: actions/cache@v2
        with:
          path: |
            .tox
            ~/.cache/pip
          key: v6-misc-tox-cache-${{ matrix.tox-environment }}-${{ hashFiles('tox.ini', 'dev-requirements.txt', 'gen-requirements.txt', 'docs-requirements.txt') }}
      - name: run tox
        run: tox -e ${{ matrix.tox-environment }}
      - name: Ensure generated code is up to date
        if: matrix.tox-environment == 'generate'
        run: git diff --exit-code || (echo 'Generated code is out of date, please run "tox -e generate" and commit the changes in this PR.' && exit 1)
